// <auto-generated />
using FinanceManagement.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceManagement.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210623202214_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinanceManagement.Models.Entities.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpenseTypeId");

                    b.Property<int>("MonthId");

                    b.Property<double>("Value");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("MonthId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FinanceManagement.Models.Entities.ExpenseType", b =>
                {
                    b.Property<int>("ExpenseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ExpenseTypeId");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("FinanceManagement.Models.Entities.Month", b =>
                {
                    b.Property<int>("MonthId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MonthId");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("FinanceManagement.Models.Entities.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MonthId");

                    b.Property<double>("Value");

                    b.HasKey("SalaryId");

                    b.HasIndex("MonthId")
                        .IsUnique();

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("FinanceManagement.Models.Entities.Expense", b =>
                {
                    b.HasOne("FinanceManagement.Models.Entities.ExpenseType", "ExpenseTypes")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinanceManagement.Models.Entities.Month", "Month")
                        .WithMany("Expenses")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinanceManagement.Models.Entities.Salary", b =>
                {
                    b.HasOne("FinanceManagement.Models.Entities.Month", "Month")
                        .WithOne("Salaries")
                        .HasForeignKey("FinanceManagement.Models.Entities.Salary", "MonthId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
